version: '3.8'

services:
  pytest-runner:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install pytest && 
      pytest -v test_funk.py"
      